### ISSUE TITLE
about datasets

### ISSUE THREAD

**Issue by hsywatchingu** [jonasricker/diffusion-model-deepfake-detection#1]
Hi jonasricker!
I wonder if the generated face dataset is included in the dataset you provided.

**Comment by jonasricker** [comment]
Hi hsywatchingu,
currently the downloadable dataset only contains LSUN bedroom images.

However, the checkpoints used to create the facial images are provided in the repositories of [LDM](https://github.com/CompVis/latent-diffusion) and [P2](https://github.com/jychoi118/P2-weighting).

**Comment by jonasricker** [comment]
The additional datasets are now also available at [Zenodo](https://zenodo.org/doi/10.5281/zenodo.10454274).
