### ISSUE TITLE
LDM and PNDM just have 40k samples each over test,train,val

### ISSUE THREAD

**Issue by kanarian** [jonasricker/diffusion-model-deepfake-detection#3]
Hi,

I have been in the process of downloading all the images from the zenodo link and I wanted to create a folder of 50k items for each of the models, so I can use them for my own experiments. However, I have noticed that LDM and PNDM only have 40k samples in total after combining all folders. I suspect this might be due to the train zip only containing 29k samples for LDM and PNDM, but I cannot say this for sure, as I do not have access to that zip anymore and downloading it again will take a long time.

Is this true or is it a mistake on my part?

**Comment by jonasricker** [comment]
Hi Arian,
I just downloaded the files again, for me all 50k samples are there for LDM and PNDM. Maybe somehow some files got lost when you merged the directories?

**Comment by kanarian** [comment]
I see, thanks for the response!
