### ISSUE TITLE
about datasets

### ISSUE THREAD

**Issue by SleeplessBegonia** [jonasricker/diffusion-model-deepfake-detection#6]
when the image is jpg,can it run?

**Comment by jonasricker** [comment]
Hi,
depending on which experiments you have to run, you might have to change this line to also accept jpg images: https://github.com/jonasricker/diffusion-model-deepfake-detection/blob/9916aa38d813d5ee5724ab92791042f8cbdda128/src/data.py#L32

Otherwise, there shouldn't be any issues.

**Comment by SleeplessBegonia** [comment]
thank u

**Comment by SleeplessBegonia** [comment]
thank u
