### ISSUE TITLE
fix a problem "ModuleNotFoundError: No module named 'seaborn._oldcore'"

### ISSUE THREAD

**Issue by keao23** [jonasricker/diffusion-model-deepfake-detection#7]
seaborn._oldcore is unavailable anymore, so it reports the above error.
I suggest changing the code of line 107-108 in the file " src/paper_utils.py" to "dashes = ["-"]*len(sns.color_palette("deep"))".

**Comment by jonasricker** [comment]
Thanks for bringing this up, apparently the function is still available and can be accessed from `seaborn._base`.
